# 1. Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

# 2. Build Stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Project files copy aur restore (Apne project folders ke naam ke mutabiq adjust karein)
COPY ["*.sln", "./"]
COPY ["AeroDesk.API/AeroDesk.API.csproj", "AeroDesk.API/"]
RUN dotnet restore

COPY . .
WORKDIR "/src/AeroDesk.API"
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

# 3. Publish Stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# 4. Final Image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AeroDesk.API.dll"]